### PR TITLE
Bump crossbeam-channel to 0.4.0

### PR DESCRIPTION
**Pull request by kjeremy**
Do a `cargo update` while we're at it.... actually should I delete the `Cargo.lock` file?

### CODE REVIEW

**Comment by matklad** [comment]
Hm, yeah, it makes sense to remove .lock. Could you also bump a version in Cargo.toml? Crossbeam-channel is a public dep

**Comment by kjeremy** [comment]
Since it's a public dep should I bump to `0.3.0`?

**Comment by matklad** [comment]
Thanks!

**Comment by matklad** [comment]
Published!

**Pull request merged**
