### PR TITLE
Add license files

### PR DESCRIPTION
**Pull request by bollwyvl**
Thanks for this project!

these were copied from the neighboring project `smol_str`:
- https://raw.githubusercontent.com/rust-analyzer/smol_str/master/LICENSE-MIT
- https://raw.githubusercontent.com/rust-analyzer/smol_str/master/LICENSE-APACHE

blocks: https://github.com/conda-forge/texlab-feedstock/pull/10

### CODE REVIEW

**Comment by lnicola** [comment]
Thanks!

bors r+

**Comment by bollwyvl** [comment]
Thank you!

**Comment by lnicola** [comment]
Can you also file a PR to bump the version? It would help with publishing a new release.

**Comment by bollwyvl** [comment]
Of course, selfishly, I'm interested in a version of the package that has _already_ shipped, as the license won't somehow get included... seems like it can wait for a future rev. Now that it's available from an official source, all my needs have been met (for _this_ package!)

That being said, happy to help: what version do you propose? And what other version spoor do i need to look out for? Changelog, etc.

**Comment by lnicola** [comment]
You can just bump the version in Cargo.toml.

**Comment by lnicola** [comment]
Aand it's published.

**Pull request merged**
